---
# tasks file for csi
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 
- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      shell: vault kv get -field=value {{ csi_kubeconfig_vault_path }}
      environment:
        VAULT_ADDR: "{{ csi_vault_address }}"
        VAULT_TOKEN: "{{ csi_vault_token }}"
      register: __kubeconfig_json

- name: Convert JSON to YAML and save to a variable
  set_fact:
    _kubeconfig_content: "{{ __kubeconfig_json.stdout | from_json | to_nice_yaml }}"

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig to /root/.kube/config
  copy:
    content: "{{ _kubeconfig_content }}"
    dest: "/root/.kube/config"
    mode: '0600'
    
- name: Create namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "hcloud-csi"

- name: Create service account
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: hcloud
        namespace: "hcloud-csi"
      stringData:
        token: "{{ csi_hcloud_api_token }}"
      

- name: Add hcloud-csi Helm repository
  when: cni_hcloud_check|bool
  kubernetes.core.helm_repository:
    name: hcloud
    repo_url: https://charts.hetzner.cloud

- name: Add longhorn Helm repository
  when: not cni_hcloud_check|bool
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn with Helm
  when: not cni_hcloud_check|bool
  community.kubernetes.helm:
    name: longhorn-system
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig: "{{ csi_kubeconfig }}"

- name: Install or Upgrade hcloud-csi-driver with Helm
  when: cni_hcloud_check|bool
  community.kubernetes.helm:
    name: hcloud-csi
    chart_ref: hcloud/hcloud-csi
    state: present
    release_namespace: hcloud-csi
    create_namespace: true
    kubeconfig: "{{ csi_kubeconfig }}"