# roles/cilium_hubble/tasks/main.yml
---
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 
#! AWX pod setup
- name: Get role token from Vault
  community.hashi_vault.vault_login:
    url: "{{ lookup('env', 'VAULT_ADDR') }}"
    auth_method: approle
    mount_point: "approle"
    role_id: "{{ ansible_hashi_vault_role_id }}"
    secret_id: "{{ ansible_hashi_vault_secret_id }}" 
  register: __login_data

- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      shell: vault kv get -field=value {{ cilium_kubeconfig_vault_path }}
      environment:
        VAULT_ADDR: "{{ lookup('env', 'VAULT_ADDR') }}"
        VAULT_TOKEN: "{{  __login_data.login.auth.client_token }}"
      register: __kubeconfig_json

- name: Convert JSON to YAML and save to a variable
  set_fact:
    _kubeconfig_content: "{{ __kubeconfig_json.stdout | from_json | to_nice_yaml }}"

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig to /root/.kube/config
  copy:
    content: "{{ _kubeconfig_content }}"
    dest: "/root/.kube/config"
    mode: '0600'
#! AWX pod setup


- name: Add Cilium repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install or upgrade Cilium Helm chart
  community.kubernetes.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_version }}"
    release_namespace: cilium
    create_namespace: true
    release_values:
      hubble:
        relay:
          enabled: "{{ cilium_hubble_relay }}"
        ui:
          enabled: "{{ cilium_hubble_ui }}"
        tls:
          auto:
            enabled: "{{ cilium_hubble_tls_auto }}"
            method: "helm"
            certValidityDuration: 1095
            
- name: Generate random username
  set_fact:
    _cilium_hubble_username: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=8') }}"

- name: Generate random password
  set_fact:
    _cilium_hubble_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"

- name: Create Kubernetes secret
  command: kubectl create secret generic save-hubble-basic-auth --from-literal=username="{{ _cilium_hubble_username }}" --from-literal=password="{{ _cilium_hubble_password }}" --namespace=cilium
  register: kubectl_output
  
- name: Install apache2-utils package on Ubuntu using apt
  when: ansible_distribution == 'Ubuntu'  # Check if the distribution is Ubuntu
  apt:
    name: apache2-utils
    state: present

- name: Install httpd-tools package on CentOS using yum
  when: ansible_distribution == 'CentOS'  # Check if the distribution is CentOS
  yum:
    name: httpd-tools
    state: present

- name: Create htpasswd file
  command: htpasswd -bc /root/htpasswd {{ _cilium_hubble_username }} {{ _cilium_hubble_password }}
  args:
    creates: "/root/htpasswd"

- name: Create Kubernetes secret from htpasswd file
  command: kubectl create secret generic hubble-basic-auth --from-file=auth=/root/htpasswd --namespace cilium
  args:
    creates: basic-auth-secret
  
- name: Copy Jinja2 template to target directory
  ansible.builtin.template:
    src: templates/ingress.j2
    dest: "/root/ingress-hubble.yml"

- name: Apply ingress configuration
  community.kubernetes.k8s:
    src: "/root/ingress-hubble.yml"
    state: present