# roles/cilium_hubble/tasks/main.yml
---

- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      ansible.builtin.set_fact:
        _kubeconfig_content: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/k8s/kubeconfig', auth_method='token', token=vault_token, url=vault_address) }}"
      environment:
        VAULT_ADDR: "{{ vault_address }}"
        VAULT_TOKEN: "{{ vault_token }}"

    - name: Write kubeconfig to /root/.kube/config
      ansible.builtin.copy:
        dest: "/tmp/config"
        content: "{{ _kubeconfig_content }}"
        mode: '0600'
    - name: Process kubeconfig with yq and write to the correct location
      ansible.builtin.shell: |
        yq eval -P /tmp/config > /root/.kube/config
      args:
        executable: /bin/bash
    - name: Secure kubeconfig file permissions
      ansible.builtin.file:
        path: "/root/.kube/config"
        owner: root
        group: root
        mode: '0600'
  tags: ['always']


- ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} repo add cilium https://helm.cilium.io/
  args:
    executable: /bin/bash

- ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} upgrade --install cilium cilium/cilium --version {{ cilium_version }} 
        --namespace cilium
        --create-namespace
        --set hubble.relay.enabled={{ cilium_hubble_relay }}
        --set hubble.ui.enabled={{ cilium_hubble_ui }} 
        --set hubble.tls.auto.enabled={{ cilium_hubble_tls_auto }}
        --set hubble.tls.auto.method=helm 
        --set hubble.tls.auto.certValidityDuration=1095
  args:
    executable: /bin/bash
- name: Generate random username
  set_fact:
    cilium_hubble_username: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=8') }}"

- name: Generate random password
  set_fact:
    cilium_hubble_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"

- name: Set environment variables
  set_fact:
    ansible_env:
      USERNAME: "{{ cilium_hubble_username }}"
      PASSWORD: "{{ cilium_hubble_password }}"

- name: Create Kubernetes secret
  command: kubectl create secret generic save-hubble-basic-auth --from-literal=username="{{ cilium_hubble_username }}" --from-literal=password="{{ cilium_hubble_password }}" --namespace=cilium
  register: kubectl_output
  
- name: Install apache2-utils package
  apt:
    name: apache2-utils
    state: present

- name: Create htpasswd file
  command: htpasswd -bc /root/htpasswd {{ cilium_hubble_username }} {{ cilium_hubble_password }}
  args:
    creates: "{{ cilium_ingress_file_path }}/htpasswd"

- name: Create Kubernetes secret from htpasswd file
  command: kubectl create secret generic hubble-basic-auth --from-file=auth={{ cilium_ingress_file_path }}/htpasswd --namespace cilium
  args:
    creates: basic-auth-secret
  
- name: Copy Jinja2 template to target directory
  ansible.builtin.template:
    src: templates/ingress.j2
    dest: "{{ cilium_ingress_file_path }}/ingress-hubble.yml"

- name: Apply ingress configuration
  ansible.builtin.command: kubectl apply -f {{ cilium_ingress_file_path }}/ingress-hubble.yml

