# roles/cilium_hubble/tasks/main.yml
---

- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      shell: vault kv get -field=value {{ prxmkuberbootstrap_cilium_kubeconfig_vault_path }}
      environment:
        VAULT_ADDR: "{{ prxmkuberbootstrap_cilium_vault_address }}"
        VAULT_TOKEN: "{{ prxmkuberbootstrap_cilium_vault_token }}"
      register: __kubeconfig_json

- name: Convert JSON to YAML and save to a variable
  set_fact:
    _kubeconfig_content: "{{ __kubeconfig_json.stdout | from_json | to_nice_yaml }}"

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig to /root/.kube/config
  copy:
    content: "{{ _kubeconfig_content }}"
    dest: "/root/.kube/config"
    mode: '0600'



- ansible.builtin.shell:
    cmd: helm --kubeconfig={{ prxmkuberbootstrap_cilium_kubeconfig }} repo add cilium https://helm.cilium.io/
  args:
    executable: /bin/bash

- name: Update Helm Repositories
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ prxmkuberbootstrap_cilium_kubeconfig }} repo update

- ansible.builtin.shell:
    cmd: helm --kubeconfig={{ prxmkuberbootstrap_cilium_kubeconfig }} upgrade --install cilium cilium/cilium --version {{ prxmkuberbootstrap_cilium_version }} 
        --namespace cilium 
        --create-namespace
        --set hubble.relay.enabled={{ prxmkuberbootstrap_cilium_hubble_relay }}
        --set hubble.ui.enabled={{ prxmkuberbootstrap_cilium_hubble_ui }} 
        --set hubble.tls.auto.enabled={{ prxmkuberbootstrap_cilium_hubble_tls_auto }}
        --set hubble.tls.auto.method=helm 
        --set hubble.tls.auto.certValidityDuration=1095
  args:
    executable: /bin/bash
- name: Generate random username
  set_fact:
    _cilium_hubble_username: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=8') }}"

- name: Generate random password
  set_fact:
    _cilium_hubble_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"

- name: Set environment variables
  set_fact:
    ansible_env:
      USERNAME: "{{ _cilium_hubble_username }}"
      PASSWORD: "{{ _cilium_hubble_password }}"

- name: Create Kubernetes secret
  command: kubectl create secret generic save-hubble-basic-auth --from-literal=username="{{ _cilium_hubble_username }}" --from-literal=password="{{ _cilium_hubble_password }}" --namespace=cilium
  register: kubectl_output
  
- name: Install apache2-utils package
  yum:
    name: httpd-tools 
    state: present

- name: Create htpasswd file
  command: htpasswd -bc /root/htpasswd {{ _cilium_hubble_username }} {{ _cilium_hubble_password }}
  args:
    creates: "{{ prxmkuberbootstrap_cilium_ingress_file_path }}/htpasswd"

- name: Create Kubernetes secret from htpasswd file
  command: kubectl create secret generic hubble-basic-auth --from-file=auth={{ prxmkuberbootstrap_cilium_ingress_file_path }}/htpasswd --namespace cilium
  args:
    creates: basic-auth-secret
  
- name: Copy Jinja2 template to target directory
  ansible.builtin.template:
    src: templates/ingress.j2
    dest: "{{ prxmkuberbootstrap_cilium_ingress_file_path }}/ingress-hubble.yml"

- name: Apply ingress configuration
  ansible.builtin.command: kubectl apply -f {{ prxmkuberbootstrap_cilium_ingress_file_path }}/ingress-hubble.yml

