---
# defaults file for cilium
#! Wariable for AWX user
cilium_kubeconfig_vault_path: # path to kube config file in vault

cilium_kubeconfig: /root/.kube/config # path to your kube config #if you are using awx, dont change it
cilium_version: 1.14.6
cilium_ingress_file_path: /root
cilium_hubble_domain: domain.uz # chnage to your domain
cilium_hubble_relay: true
cilium_hubble_ui: true
cilium_hubble_tls_auto: true 