---
# defaults file for cilium

prxmkuberbootstrap_cilium_vault_address: http://18.212.236.56:8200
prxmkuberbootstrap_cilium_vault_token: hvs.DpMVigg8GjQxhEdPFAYZpwz7

prxmkuberbootstrap_cilium_kubeconfig_vault_path: secret/k8s/kubeconfig
prxmkuberbootstrap_cilium_kubeconfig: /root/.kube/config
prxmkuberbootstrap_cilium_version: 1.14.6
prxmkuberbootstrap_cilium_ingress_file_path: /root
prxmkuberbootstrap_cilium_hubble_domain: hubble.bexruzdev.uz
prxmkuberbootstrap_cilium_hubble_relay: true
prxmkuberbootstrap_cilium_hubble_ui: true
prxmkuberbootstrap_cilium_hubble_tls_auto: true 