---
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 

- name: Get role token from Vault
  community.hashi_vault.vault_login:
    url: "{{ lookup('env', 'VAULT_ADDR') }}"
    auth_method: approle
    mount_point: "approle"
    role_id: "{{ ansible_hashi_vault_role_id }}"
    secret_id: "{{ ansible_hashi_vault_secret_id }}" 
  register: __login_data

- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      shell: vault kv get -field=value {{ certmanager_kubeconfig_vault_path }}
      environment:
        VAULT_ADDR: "{{ certmanager_vault_address }}"
        VAULT_TOKEN: "{{  __login_data.login.auth.client_token }}"
      register: __kubeconfig_json

- name: Convert JSON to YAML and save to a variable
  set_fact:
    _kubeconfig_content: "{{ __kubeconfig_json.stdout | from_json | to_nice_yaml }}"

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig to /root/.kube/config
  copy:
    content: "{{ _kubeconfig_content }}"
    dest: "/root/.kube/config"
    mode: '0600'

- name: Add Jetstack Helm Repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install or upgrade cert-manager with custom values
  community.kubernetes.helm:
    kubeconfig: "{{ certmanager_kubeconfig }}"
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    chart_version: "{{ certmanager_version }}"
    release_values:
      installCRDs: true
      prometheus:
        enabled: false


- name: Create Issuer YAML File
  template:
    src: issuer.yml.j2
    dest: /root/issuer.yml


- name: Apply Issuer Configuration
  ansible.builtin.command:
    cmd: kubectl apply -f /root/issuer.yml -n cert-managerer
  args:
    executable: /bin/bash

- name: Delete a specific file
  ansible.builtin.file:
    path: /root/issuer.yml
    state: absent 
