---
- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      shell: vault kv get -field=value {{ kubeconfig_vault_path }}
      environment:
        VAULT_ADDR: "{{ vault_address }}"
        VAULT_TOKEN: "{{ vault_token }}"
      register: __kubeconfig_json

- name: Convert JSON to YAML and save to a variable
  set_fact:
    _kubeconfig_content: "{{ __kubeconfig_json.stdout | from_json | to_nice_yaml }}"

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig to /root/.kube/config
  copy:
    content: "{{ _kubeconfig_content }}"
    dest: "/root/.kube/config"
    mode: '0600'
    
- name: Add Ingress-Nginx Helm repository
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  args:
    executable: /bin/bash

- name: Update Helm repositories
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} repo update
  args:
    executable: /bin/bash

- name: Install nginx-ingress with Helm
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} install nginx-ingress ingress-nginx/ingress-nginx 
        --namespace ingress-nginx 
        --create-namespace
        --set controller.hostPort.enabled={{ nginx_ingress_controller_hostPort_enabled }} 
        --set controller.hostNetwork={{ nginx_ingress_controller_hostNetwork }} 
        --set controller.service.type={{ nginx_ingress_controller_service_type }} 
        --set controller.kind={{ nginx_ingress_controller_kind }}
  args:
    executable: /bin/bash
  
