---
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 

- name: Retrieve kubeconfig from Vault and write to a user-writable location
  block:
    - name: Retrieve kubeconfig from Vault
      shell: vault kv get -field=value {{ ingress_nginx_kubeconfig_vault_path }}
      environment:
        VAULT_ADDR: "{{ ingress_nginx_vault_address }}"
        VAULT_TOKEN: "{{ ingress_nginx_vault_token }}"
      register: __kubeconfig_json

- name: Convert JSON to YAML and save to a variable
  set_fact:
    _kubeconfig_content: "{{ __kubeconfig_json.stdout | from_json | to_nice_yaml }}"

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig to /root/.kube/config
  copy:
    content: "{{ _kubeconfig_content }}"
    dest: "/root/.kube/config"
    mode: '0600'
    
- name: Add Ingress-Nginx Helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install nginx-ingress with Helm
  community.kubernetes.helm:
    kubeconfig: "{{ ingress_nginx_kubeconfig }}"
    name: nginx-ingress
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    release_values:
      controller:
        hostPort:
          enabled: "{{ ingress_nginx_hostPort_enabled }}"
        hostNetwork: "{{ ingress_nginx_hostNetwork }}"
        service:
          type: "{{ ingress_nginx_service_type }}"
        kind: "{{ ingress_nginx_kind }}"

