---
# defaults file for csi
prxmkuberbootstrap_csi_vault_address: http://18.212.236.56:8200
prxmkuberbootstrap_csi_vault_token: hvs.DpMVigg8GjQxhEdPFAYZpwz7
prxmkuberbootstrap_csi_kubeconfig_vault_path: secret/k8s/kubeconfig

prxmkuberbootstrap_cni_hcloud_check: true   # set to "true" for use hcloud-csi-driver 
prxmkuberbootstrap_csi_kubeconfig: /root/.kube/config
prxmkuberbootstrap_csi_hcloud_api_token: "VSTtj0tjwxD3lCBv1ZoJjkuhCNThehmw1KOFbRK53BO3FJOt0TvqLSlKfBZ9bhsc"